version: '3.7'

services:

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=7mRWsvXDs6k89Qf
    ports:
      - '5432:5432'
